### ISSUE TITLE
Firefox compatilibility

### ISSUE THREAD

**Issue by tibastral** [billstclair/elm-code-mirror#1]
Doesn't work on FF :)

**Comment by billstclair** [comment]
Known problem. There are instructions for what to do to make it work in Firefox at https://github.com/billstclair/elm-code-mirror#compatibility. You can either set the `dom.webcomponents.customelements.enabled` property in `about:config`, or uncomment the code in `index.html` that loads a polyfill.

It doesn't work at all in IE or Edge. They may be possible to fix, but the polyfill alone didn't do it, so unless somebody motivates me, e.g. with a working pull request, I don't plan to fix that.
